---
title: "format spatial GEX data (semla)"
author: "Victoria Muliadi"
date: "2024-04-12"
output: html_document
---

Preprocess spatial GEX data and create Seurat object using 'semla' package

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r load packages}
library(semla)
library(readr)
```

## Load spatial GEX data

BCSA3
barcodes/visium ID
(1) bc2073 / V19T26-031_C1 --> A2 (consecutive A1 --> V19T26-031_D1)
(2) bc2081 / V19T26-032_D1 --> C1
(3) bc2089 / V19T26-032_C1 --> C2
(4) bc2002 / V19T26-032_B1 --> D1 *
(5) bc2010 / V19T26-032_A1 --> D2 *

```{r load spatial gex data}

root.path <- "C:/Users/victo/Downloads/BC_spaceranger/"

visium_id <- "V19T26-032_A1"
tumor_area <- "BC-SA3-D"
section <- "D2"

feature.matrix.path <- "/filtered_feature_bc_matrix.h5"
spotfile.path <- "/spatial/tissue_positions_list.csv"
img.path <- "/spatial/tissue_hires_image.png"
json.path <- "/spatial/scalefactors_json.json"

samples <- paste0(root.path, visium_id, feature.matrix.path)
imgs <- paste0(root.path, visium_id, img.path)
spotfiles <- paste0(root.path, visium_id, spotfile.path)
json <- paste0(root.path, visium_id, json.path)

infoTable <- tibble(samples, imgs, spotfiles, json,
                    visium_id, tumor_area, section)

se.d2 <- ReadVisiumData(infoTable) # 33538 features, 4816 spots

# nCount: UMI (for columns / spots)
# nFeature: gene (for columns / spots)

## criteria:
# spots (columns): >= 500 UMI counts (lower to 300 if needed?)

keep.spots <- colnames(se.d2)[se.d2$nCount_Spatial >= 500]

# genes (rows): >= 100 UMI counts + expressed in >= 5 spots in dataset
# total expression / UMI count for the gene across all spots:
nCount.UMI <- Matrix::rowSums(GetAssayData(se.d2))

# number of spots where gene is observed:
nObs.genes <- Matrix::rowSums(GetAssayData(se.d2) > 0)

keep.genes <- rownames(se.d2)[nCount.UMI >= 100 & nObs.genes >= 5]

## filter mitochondrial and ribosomal genes
keep.genes <- keep.genes[!grepl("MALAT1", keep.genes)]
keep.genes <- keep.genes[!grepl("^(MT-|RPL|RPS)", keep.genes)]

# subset
se.d2 <- SubsetSTData(se.d2, spots = keep.spots, features = keep.genes)

se.d2 # 11774 features, 4705 spots

```


```{r load H&E images}
se <- LoadImages(se)

ImagePlot(se)

```

```{r save seurat object}
write_rds(se, "C:/Users/victo/Downloads/spatialVDJ/scripts/sample_analysis/BCSA3_tumD.rds")

write_rds(se.d1, "C:/Users/victo/Downloads/spatialVDJ/scripts/sample_analysis/BCSA3_D1.rds")

write_rds(se.d2, "C:/Users/victo/Downloads/spatialVDJ/scripts/sample_analysis/BCSA3_D2.rds")

```



